In [20]:
import pandas as pd
import numpy as np

In [14]:
file = pd.read_excel(r"C:\Users\cex\Desktop\moknowslife\Workout Menu .xlsx", header=None)
file

,0,1,2,3,4,5,6,7,8,9,...,25,26,27,28,29,30,31,32,33,34
0,Base,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Warm up 1,NaN,NaN,NaN,NaN,NaN,Mobility 1,NaN,NaN,Cool Down 1,...,NaN,NaN,Posture 1,NaN,NaN,Sprint Reaction 1,NaN,NaN,Wall Drills 1,NaN
4,Scoops,25m,NaN,Frankenstiens,25m,NaN,Front/Side Leg Swings,2x25,NaN,Flamingos,...,10,NaN,Wall Holds,3x30s,NaN,Voice Push Up Start,4x10m,NaN,Lean Hold,4x30s
5,Flamingos,25m,NaN,Butt Kickers,25m,NaN,Ankle Alphabet,x2,NaN,Swwops,...,10,NaN,Chin Tuck Hold,3x10,NaN,Visual Drop Start,4x10m,NaN,Iso Holds,4x10s
6,Knee hugs,25m,NaN,Knee Pulls,25m,NaN,Knee Pushes,x2,NaN,Quad Pulls,...,2x50,NaN,Deadbug + Wall Press,3x10,NaN,Mirror Shuffle,3x15s,NaN,March,2x10
7,Mummy Walks,25m,NaN,Arm Circles,25m,NaN,Split Squats,4x25s,NaN,5-Way Lunge,...,2x50,NaN,Pelvic Thrust Slow,3x10,NaN,Head Turn + Sprint,3x10m,NaN,Wall Switch (1-1),2x10
8,F Lunge,25m,NaN,B Lunge,25m,NaN,Split Squat step ins F,x5,NaN,Laying Pigeon,...,20s/ 10s. 4,NaN,Bird Dog Hold,2x20s,NaN,Light Tap Reaction,3x15m,NaN,NaN,NaN
9,Fire Hydrants,20,NaN,NaN,NaN,NaN,Split Squat step ins B,x5,NaN,Hamstring Lean Back,...,2x100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Carioca,25m,NaN,High Knees,25m,NaN,Ankle Rotations Clockwise,2x25s,NaN,Calf Stetch,...,2x10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,A March,25m,NaN,A Skip,25m,NaN,Ankle Rotations Counter,2x25s,NaN,Side Stretch,...,2x10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,B March,25m,NaN,B Skip,NaN,NaN,Knee Rotations Clockwise,2x25s,NaN,Side Lunge,...,2x10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Build up,6,NaN,Striders,4,NaN,Knee Rotations Counter,2x25s,NaN,It Band Stretch,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,F Leg Swings,25,NaN,Lat Leg Swing,25,NaN,Calf Stretch standing,2x25s,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,Calf Stretch Ground,2x25s,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,It Band Stretch,2x25s,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Build,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Warm up 2,NaN,NaN,NaN,NaN,NaN,Mobility 2,NaN,NaN,Cool Down 2,...,NaN,NaN,Posture 2,NaN,NaN,Sprint Reaction 2,NaN,NaN,Wall Drills 2,NaN
21,Scoops,30m,NaN,Frankenstiens,30m,NaN,Front/Side Leg Swings,3x25,NaN,Flamingos,...,2x15,NaN,Wall Holds,3x30s,NaN,Voice Push Up Start,6x10m,NaN,Lean Hold,4x45s
22,Flamingos,30m,NaN,Butt Kickers,30m,NaN,Ankle Alphabet,x3,NaN,Swwops,...,20,NaN,Chin Tuck Hold,3x10,NaN,Visual Drop Start,6x10m,NaN,Iso Holds,4x145s
23,Knee hugs,30m,NaN,Knee Pulls,30m,NaN,Knee Pushes,x3,NaN,Quad Pulls,...,3x50,NaN,Deadbug + Wall Press,3x10,NaN,Mirror Shuffle,6x15s,NaN,March,4x15
24,Mummy Walks,30m,NaN,Arm Circles,30m,NaN,Split Squats,6x25s,NaN,5-Way Lunge,...,3x50,NaN,Pelvic Thrust Slow,3x10,NaN,Head Turn + Sprint,6x10m,NaN,Wall Switch (1-1),4x10
25,F Lunge,30m,NaN,B Lunge,30m,NaN,Split Squat step ins F,x10,NaN,Laying Pigeon,...,(6)20s/ 10s,NaN,Bird Dog Hold,2x20s,NaN,Light Tap Reaction,6x15m,NaN,Wall Switch (1-2),4x10
26,Fire Hydrants,25,NaN,F/B Circls,25,NaN,Split Squat step ins B,x10,NaN,Hamstring Lean Back,...,3x100,NaN,Fire Hydrant Hold,4x10s,NaN,NaN,NaN,NaN,Wall Switch (1-3),4x10
27,Carioca,30m,NaN,High Knees,30m,NaN,Ankle Rotations Clockwise,3x25s,NaN,Calf Stetch,...,3x10,NaN,Wall Slide w/ PVC,2x10,NaN,NaN,NaN,NaN,SL Leg Snap,2x10
28,A March,30m,NaN,A Skip,Peak,NaN,Ankle Rotations Counter,3x25s,NaN,Side Stretch,...,3x10,NaN,Splt Squat Chop,2x10,NaN,NaN,NaN,NaN,Wall March W/ Clap,4x10
29,B March,30m,NaN,B Skip,NaN,NaN,Knee Rotations Clockwise,3x25s,NaN,Side Lunge,...,3x10,NaN,Glute Bridge,2x10,NaN,NaN,NaN,NaN,NaN,NaN
30,Build up,8,NaN,Striders,6,NaN,Knee Rotations Counter,3x25s,NaN,It Band Stretch,...,2x10,NaN,Wall March,2x25,NaN,NaN,NaN,NaN,NaN,NaN
31,F Leg Swings,25,NaN,Lat Leg Swing,20,NaN,Calf Stretch standing,3x25s,NaN,NaN,...,2x10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,NaN,NaN,NaN,Calf Stretch Ground,3x25s,NaN,NaN,...,2x20m,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN,NaN,NaN,It Band Stretch,3x25s,NaN,NaN,...,2x10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,Peak,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,Warm up 3 (Tempo),NaN,NaN,NaN,NaN,NaN,Mobility 3,NaN,NaN,Cool Down 3 (Twice),...,NaN,NaN,Posture 3,NaN,NaN,Sprint Reaction 3,NaN,NaN,Wall Drills 3,NaN
38,Scoops,30m,NaN,Frankenstiens,30m,NaN,Front/Side Leg Swings,4x25,NaN,Flamingos,...,3x15,NaN,Wall Holds,4x30s,NaN,Voice Push Up Start,8x10m,NaN,Lean Hold,4x1 min
39,Flamingos,30m,NaN,Butt Kickers,30m,NaN,Ankle Alphabet Blind,x4,NaN,Swwops,...,300,NaN,Chin Tuck Hold,4x10,NaN,Visual Drop Start,8x10m,NaN,Iso Holds,4x1 min
40,Knee hugs,30m,NaN,Knee Pulls,30m,NaN,Knee Pushes,x4,NaN,Quad Pulls,...,4x50,NaN,Deadbug + Wall Press,4x10,NaN,Mirror Shuffle,8x15s,NaN,March,4x20
41,Mummy Walks,30m,NaN,Arm Circles,30m,NaN,Split Squats,8x25s,NaN,5-Way Lunge,...,4x50,NaN,Pelvic Thrust Slow,4x10,NaN,Head Turn + Sprint,8x10m,NaN,Wall Switch (1-1),4x20
42,F Lunge,30m,NaN,B Lunge,30m,NaN,Split Squat step ins F,x15,NaN,Laying Pigeon,...,20s/ 10s. 8,NaN,Bird Dog Hold,4x20s,NaN,Light Tap Reaction,8x15m,NaN,Wall Switch (1-2),4x20
43,Fire Hydrants,30,NaN,F/B Circls,30,NaN,Split Squat step ins B,x15,NaN,Hamstring Lean Back,...,4x100,NaN,Fire Hydrant Hold,4x10s,NaN,NaN,NaN,NaN,Wall Switch (1-3),4x20
44,Donkey Kicks,30,NaN,Side Raise,30,NaN,Ankle Rotations Clockwise,4x25s,NaN,Calf Stetch,...,4x10,NaN,Wall Slide w/ PVC,4x10,NaN,NaN,NaN,NaN,SL Leg Snap,4x15
45,Carioca,30m,NaN,High Knees,30m,NaN,Ankle Rotations Counter,4x25s,NaN,Side Stretch,...,4x10,NaN,Splt Squat Chop,4x10,NaN,NaN,NaN,NaN,Wall March W/ Clap,4x15
46,A March,30m,NaN,A Skip,30m,NaN,Knee Rotations Clockwise,4x25s,NaN,Side Lunge,...,4x10,NaN,Glute Bridge,4x10,NaN,NaN,NaN,NaN,Wall Switch To Drive,(4)4x20s
47,B March,30m,NaN,B Skip,NaN,NaN,Knee Rotations Counter,4x25s,NaN,It Band Stretch,...,4x10,NaN,Wall March,4x25,NaN,NaN,NaN,NaN,Drive,(6)20s/10s
48,Build up,8,NaN,Striders,8,NaN,Calf Stretch standing,4x25s,NaN,NaN,...,4x10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,F Leg Swings,30,NaN,Lat Leg Swing,30,NaN,Calf Stretch Ground,4x25s,NaN,NaN,...,4x20m,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,NaN,NaN,NaN,NaN,NaN,NaN,It Band Stretch Reach,4x25s,NaN,NaN,...,4x10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,Finish,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
file_dff = file.dropna(how='all')
file_df = file_dff.dropna(axis=1, how='all')
file_df

,0,1,3,4,6,7,9,10,12,13,...,21,22,24,25,27,28,30,31,33,34
0,Base,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Warm up 1,NaN,NaN,NaN,Mobility 1,NaN,Cool Down 1,NaN,Hips 1,NaN,...,Sled 1 (780m),NaN,Plyo 1,NaN,Posture 1,NaN,Sprint Reaction 1,NaN,Wall Drills 1,NaN
4,Scoops,25m,Frankenstiens,25m,Front/Side Leg Swings,2x25,Flamingos,25yds,Fire Hydrants,2x10,...,ISO Hold Start,4x20m,Push-Up Start → 5 Step Sprint,10,Wall Holds,3x30s,Voice Push Up Start,4x10m,Lean Hold,4x30s
5,Flamingos,25m,Butt Kickers,25m,Ankle Alphabet,x2,Swwops,25yds,Clams,2x10,...,Sled Walk Push,2x100m,Falling Start,10,Chin Tuck Hold,3x10,Visual Drop Start,4x10m,Iso Holds,4x10s
6,Knee hugs,25m,Knee Pulls,25m,Knee Pushes,x2,Quad Pulls,25yds,Fire Hydrant Raise,2x10,...,Eccentric Sled Pull B,2x20m,Wall March,2x50,Deadbug + Wall Press,3x10,Mirror Shuffle,3x15s,March,2x10
7,Mummy Walks,25m,Arm Circles,25m,Split Squats,4x25s,5-Way Lunge,25s,R Leg Scissors,2x10,...,Sled Push,4x50m,Wall Swithces,2x50,Pelvic Thrust Slow,3x10,Head Turn + Sprint,3x10m,Wall Switch (1-1),2x10
8,F Lunge,25m,B Lunge,25m,Split Squat step ins F,x5,Laying Pigeon,25s,L Leg Scissors,2x10,...,Sled March,3x20m,Wall Runs,20s/ 10s. 4,Bird Dog Hold,2x20s,Light Tap Reaction,3x15m,NaN,NaN
9,Fire Hydrants,20,NaN,NaN,Split Squat step ins B,x5,Hamstring Lean Back,25s,R Leg Circles,2x10,...,Sled Run,4x50m,Claw Technique,2x100,NaN,NaN,NaN,NaN,NaN,NaN
10,Carioca,25m,High Knees,25m,Ankle Rotations Clockwise,2x25s,Calf Stetch,25s,L Leg Scissors,2x10,...,NaN,NaN,Lunge Jump Cycles,2x10,NaN,NaN,NaN,NaN,NaN,NaN
11,A March,25m,A Skip,25m,Ankle Rotations Counter,2x25s,Side Stretch,25s,Seated Hurdle Switch,2x10,...,NaN,NaN,SL Hops,2x10,NaN,NaN,NaN,NaN,NaN,NaN
12,B March,25m,B Skip,NaN,Knee Rotations Clockwise,2x25s,Side Lunge,25s,Donkey Kicks,2x10,...,NaN,NaN,Ankle Hops,2x10,NaN,NaN,NaN,NaN,NaN,NaN
13,Build up,6,Striders,4,Knee Rotations Counter,2x25s,It Band Stretch,25s,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,F Leg Swings,25,Lat Leg Swing,25,Calf Stretch standing,2x25s,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,Calf Stretch Ground,2x25s,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,It Band Stretch,2x25s,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Build,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Warm up 2,NaN,NaN,NaN,Mobility 2,NaN,Cool Down 2,NaN,Hips 2,NaN,...,Sled 2,NaN,Plyo 2,NaN,Posture 2,NaN,Sprint Reaction 2,NaN,Wall Drills 2,NaN
21,Scoops,30m,Frankenstiens,30m,Front/Side Leg Swings,3x25,Flamingos,30yds,Fire Hydrants,3x12,...,ISO Hold Start,6x20m,Push-Up Start → 5 Step Sprint,2x15,Wall Holds,3x30s,Voice Push Up Start,6x10m,Lean Hold,4x45s
22,Flamingos,30m,Butt Kickers,30m,Ankle Alphabet,x3,Swwops,30yds,Clams,3x12,...,Sled Walk Push,3x100m,Falling Start,20,Chin Tuck Hold,3x10,Visual Drop Start,6x10m,Iso Holds,4x145s
23,Knee hugs,30m,Knee Pulls,30m,Knee Pushes,x3,Quad Pulls,30yds,Fire Hydrant Raise,3x12,...,Eccentric Sled Pull B,4x20m,Wall March,3x50,Deadbug + Wall Press,3x10,Mirror Shuffle,6x15s,March,4x15
24,Mummy Walks,30m,Arm Circles,30m,Split Squats,6x25s,5-Way Lunge,30s,R Leg Scissors,3x12,...,Sled Push,6x50m,Wall Swithces,3x50,Pelvic Thrust Slow,3x10,Head Turn + Sprint,6x10m,Wall Switch (1-1),4x10
25,F Lunge,30m,B Lunge,30m,Split Squat step ins F,x10,Laying Pigeon,30s,L Leg Scissors,3x12,...,Sled March,6x20m,Wall Runs,(6)20s/ 10s,Bird Dog Hold,2x20s,Light Tap Reaction,6x15m,Wall Switch (1-2),4x10
26,Fire Hydrants,25,F/B Circls,25,Split Squat step ins B,x10,Hamstring Lean Back,30s,R Leg Circles,3x12,...,Sled Run,6x50m,Claw Technique,3x100,Fire Hydrant Hold,4x10s,NaN,NaN,Wall Switch (1-3),4x10
27,Carioca,30m,High Knees,30m,Ankle Rotations Clockwise,3x25s,Calf Stetch,30s,L Leg Scissors,3x12,...,Sled Sprint Drop-In,3x20m,Lunge Jump Cycles,3x10,Wall Slide w/ PVC,2x10,NaN,NaN,SL Leg Snap,2x10
28,A March,30m,A Skip,Peak,Ankle Rotations Counter,3x25s,Side Stretch,30s,Seated Hurdle Switch,3x12,...,SL Sled March,3x15,SL Hops,3x10,Splt Squat Chop,2x10,NaN,NaN,Wall March W/ Clap,4x10
29,B March,30m,B Skip,NaN,Knee Rotations Clockwise,3x25s,Side Lunge,30ss,Donkey Kicks,3x12,...,Bckpedal Sled Pull,3x20m,Ankle Hops,3x10,Glute Bridge,2x10,NaN,NaN,NaN,NaN
30,Build up,8,Striders,6,Knee Rotations Counter,3x25s,It Band Stretch,30s,NaN,NaN,...,Partner Sled Sprint,4x10m,Dept Drop to Explode,2x10,Wall March,2x25,NaN,NaN,NaN,NaN
31,F Leg Swings,25,Lat Leg Swing,20,Calf Stretch standing,3x25s,NaN,NaN,NaN,NaN,...,NaN,NaN,Hurdle Hop Low to High,2x10,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,NaN,Calf Stretch Ground,3x25s,NaN,NaN,NaN,NaN,...,NaN,NaN,Bounding,2x20m,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN,It Band Stretch,3x25s,NaN,NaN,NaN,NaN,...,NaN,NaN,Step Up Hops,2x10,NaN,NaN,NaN,NaN,NaN,NaN
34,Peak,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,Warm up 3 (Tempo),NaN,NaN,NaN,Mobility 3,NaN,Cool Down 3 (Twice),NaN,Hips 3 (Hold),NaN,...,Sled 3,NaN,Plyo 3,NaN,Posture 3,NaN,Sprint Reaction 3,NaN,Wall Drills 3,NaN
38,Scoops,30m,Frankenstiens,30m,Front/Side Leg Swings,4x25,Flamingos,35yds,Fire Hydrants,4x12,...,ISO Hold Start,8x20m,Push-Up Start → 5 Step Sprint,3x15,Wall Holds,4x30s,Voice Push Up Start,8x10m,Lean Hold,4x1 min
39,Flamingos,30m,Butt Kickers,30m,Ankle Alphabet Blind,x4,Swwops,35yds,Clams,4x12,...,Sled Walk Push,6x100m,Falling Start,300,Chin Tuck Hold,4x10,Visual Drop Start,8x10m,Iso Holds,4x1 min
40,Knee hugs,30m,Knee Pulls,30m,Knee Pushes,x4,Quad Pulls,35yds,Fire Hydrant Raise,4x12,...,Eccentric Sled Pull B,6x20m,Wall March,4x50,Deadbug + Wall Press,4x10,Mirror Shuffle,8x15s,March,4x20
41,Mummy Walks,30m,Arm Circles,30m,Split Squats,8x25s,5-Way Lunge,35s,R Leg Scissors,4x12,...,Sled Push,6x50m,Wall Swithces,4x50,Pelvic Thrust Slow,4x10,Head Turn + Sprint,8x10m,Wall Switch (1-1),4x20
42,F Lunge,30m,B Lunge,30m,Split Squat step ins F,x15,Laying Pigeon,35s,L Leg Scissors,4x12,...,Sled March,6x20m,Wall Runs,20s/ 10s. 8,Bird Dog Hold,4x20s,Light Tap Reaction,8x15m,Wall Switch (1-2),4x20
43,Fire Hydrants,30,F/B Circls,30,Split Squat step ins B,x15,Hamstring Lean Back,35s,R Leg Circles,4x12,...,Sled Run,6x50m,Claw Technique,4x100,Fire Hydrant Hold,4x10s,NaN,NaN,Wall Switch (1-3),4x20
44,Donkey Kicks,30,Side Raise,30,Ankle Rotations Clockwise,4x25s,Calf Stetch,35s,L Leg Scissors,4x12,...,Sled Sprint Drop-In,4x20m,Lunge Jump Cycles,4x10,Wall Slide w/ PVC,4x10,NaN,NaN,SL Leg Snap,4x15
45,Carioca,30m,High Knees,30m,Ankle Rotations Counter,4x25s,Side Stretch,35s,Seated Hurdle Switch,4x12,...,SL Sled March,4x20m,SL Hops,4x10,Splt Squat Chop,4x10,NaN,NaN,Wall March W/ Clap,4x15
46,A March,30m,A Skip,30m,Knee Rotations Clockwise,4x25s,Side Lunge,35s,Donkey Kicks,4x12,...,Bckpedal Sled Pull,4x20m,Ankle Hops,4x10,Glute Bridge,4x10,NaN,NaN,Wall Switch To Drive,(4)4x20s
47,B March,30m,B Skip,NaN,Knee Rotations Counter,4x25s,It Band Stretch,35s,NaN,NaN,...,Partner Sled Sprint,6x10m,Dept Drop to Explode,4x10,Wall March,4x25,NaN,NaN,Drive,(6)20s/10s
48,Build up,8,Striders,8,Calf Stretch standing,4x25s,NaN,NaN,NaN,NaN,...,NaN,NaN,Hurdle Hop Low to High,4x10,NaN,NaN,NaN,NaN,NaN,NaN
49,F Leg Swings,30,Lat Leg Swing,30,Calf Stretch Ground,4x25s,NaN,NaN,NaN,NaN,...,NaN,NaN,Bounding,4x20m,NaN,NaN,NaN,NaN,NaN,NaN
50,NaN,NaN,NaN,NaN,It Band Stretch Reach,4x25s,NaN,NaN,NaN,NaN,...,NaN,NaN,Step Up Hops To Hold,4x10,NaN,NaN,NaN,NaN,NaN,NaN
51,Finish,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [38]:
file_df.index(0)

TypeError: 'Index' object is not callable

In [42]:
# indexes = []
# for n in list(file_df.columns):
#     if 'Base' in file_df[n]:
#         indexes.append(n)
#     if 'Build' in file_df[n]:
#         indexes.append(n)
#     if 'Peak' in file_df[n]:
#         indexes.append(n)

keys = ['Base', 'Build', 'Peak']

indexes = [
    col for col in file_df.index
    if file_df.loc[col].astype(str).str.contains('|'.join(keys), na=False).any()
]

indexes

[0, 13, 17, 28, 30, 34, 48]

In [221]:
#final_indexes = [0,17,34]
base_dff = file_df.loc[1:16].reset_index().drop('index', axis=1)
base_df = base_dff[1:] 
base_df.columns = base_dff.iloc[0]
build_dff = file_df.loc[18:33].reset_index().drop('index', axis=1)
build_df = build_dff[1:]
build_df.columns = build_dff.iloc[0]
peak_dff = file_df.loc[35:50].reset_index().drop('index', axis=1)
peak_df = peak_dff[1:]
peak_df.columns = peak_dff.iloc[0]
peak_df
build_df
base_df

,Warm up 1,NaN,NaN,NaN,Mobility 1,NaN,Cool Down 1,NaN,Hips 1,NaN,...,Sled 1 (780m),NaN,Plyo 1,NaN,Posture 1,NaN,Sprint Reaction 1,NaN,Wall Drills 1,NaN
1,Scoops,25m,Frankenstiens,25m,Front/Side Leg Swings,2x25,Flamingos,25yds,Fire Hydrants,2x10,...,ISO Hold Start,4x20m,Push-Up Start → 5 Step Sprint,10,Wall Holds,3x30s,Voice Push Up Start,4x10m,Lean Hold,4x30s
2,Flamingos,25m,Butt Kickers,25m,Ankle Alphabet,x2,Swwops,25yds,Clams,2x10,...,Sled Walk Push,2x100m,Falling Start,10,Chin Tuck Hold,3x10,Visual Drop Start,4x10m,Iso Holds,4x10s
3,Knee hugs,25m,Knee Pulls,25m,Knee Pushes,x2,Quad Pulls,25yds,Fire Hydrant Raise,2x10,...,Eccentric Sled Pull B,2x20m,Wall March,2x50,Deadbug + Wall Press,3x10,Mirror Shuffle,3x15s,March,2x10
4,Mummy Walks,25m,Arm Circles,25m,Split Squats,4x25s,5-Way Lunge,25s,R Leg Scissors,2x10,...,Sled Push,4x50m,Wall Swithces,2x50,Pelvic Thrust Slow,3x10,Head Turn + Sprint,3x10m,Wall Switch (1-1),2x10
5,F Lunge,25m,B Lunge,25m,Split Squat step ins F,x5,Laying Pigeon,25s,L Leg Scissors,2x10,...,Sled March,3x20m,Wall Runs,20s/ 10s. 4,Bird Dog Hold,2x20s,Light Tap Reaction,3x15m,NaN,NaN
6,Fire Hydrants,20,NaN,NaN,Split Squat step ins B,x5,Hamstring Lean Back,25s,R Leg Circles,2x10,...,Sled Run,4x50m,Claw Technique,2x100,NaN,NaN,NaN,NaN,NaN,NaN
7,Carioca,25m,High Knees,25m,Ankle Rotations Clockwise,2x25s,Calf Stetch,25s,L Leg Scissors,2x10,...,NaN,NaN,Lunge Jump Cycles,2x10,NaN,NaN,NaN,NaN,NaN,NaN
8,A March,25m,A Skip,25m,Ankle Rotations Counter,2x25s,Side Stretch,25s,Seated Hurdle Switch,2x10,...,NaN,NaN,SL Hops,2x10,NaN,NaN,NaN,NaN,NaN,NaN
9,B March,25m,B Skip,NaN,Knee Rotations Clockwise,2x25s,Side Lunge,25s,Donkey Kicks,2x10,...,NaN,NaN,Ankle Hops,2x10,NaN,NaN,NaN,NaN,NaN,NaN
10,Build up,6,Striders,4,Knee Rotations Counter,2x25s,It Band Stretch,25s,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,F Leg Swings,25,Lat Leg Swing,25,Calf Stretch standing,2x25s,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,Calf Stretch Ground,2x25s,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,It Band Stretch,2x25s,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [222]:
def df_columns(df, phase):
    columns = [
        'Warm up', 'Repetition', 'Warm up', 'Repetition', 'Mobility',
        'Repetition', 'Cool Down', 'Repetition', 'Hips', 'Repetition',
        'Core', 'Repetition', 'Med Ball', 'Repetition', 'Sled (780m)',
        'Repetition', 'Plyo', 'Repetition', 'Posture', 'Repetition',
        'Sprint Reaction', 'Repetition', 'Wall Drills', 'Repetition'
    ]

    suffix_map = {
        "base": "1",
        "build": "2",
        "peak": "3"
    }

    df.columns = columns
    suffix = suffix_map.get(phase.lower())
    if suffix is None:
        raise ValueError("phase must be 'base', 'build', or 'peak'")

    new_df_columns = [col + suffix if col != 'Repetition' else col 
                      for col in columns]

    df.columns = new_df_columns
    return df


base_dff = df_columns(base_df, phase='base')
build_dff = df_columns(build_df, phase='build')
peak_dff = df_columns(peak_df, phase='peak')

In [223]:
base_dff

,Warm up1,Repetition,Warm up1,Repetition,Mobility1,Repetition,Cool Down1,Repetition,Hips1,Repetition,...,Sled (780m)1,Repetition,Plyo1,Repetition,Posture1,Repetition,Sprint Reaction1,Repetition,Wall Drills1,Repetition
1,Scoops,25m,Frankenstiens,25m,Front/Side Leg Swings,2x25,Flamingos,25yds,Fire Hydrants,2x10,...,ISO Hold Start,4x20m,Push-Up Start → 5 Step Sprint,10,Wall Holds,3x30s,Voice Push Up Start,4x10m,Lean Hold,4x30s
2,Flamingos,25m,Butt Kickers,25m,Ankle Alphabet,x2,Swwops,25yds,Clams,2x10,...,Sled Walk Push,2x100m,Falling Start,10,Chin Tuck Hold,3x10,Visual Drop Start,4x10m,Iso Holds,4x10s
3,Knee hugs,25m,Knee Pulls,25m,Knee Pushes,x2,Quad Pulls,25yds,Fire Hydrant Raise,2x10,...,Eccentric Sled Pull B,2x20m,Wall March,2x50,Deadbug + Wall Press,3x10,Mirror Shuffle,3x15s,March,2x10
4,Mummy Walks,25m,Arm Circles,25m,Split Squats,4x25s,5-Way Lunge,25s,R Leg Scissors,2x10,...,Sled Push,4x50m,Wall Swithces,2x50,Pelvic Thrust Slow,3x10,Head Turn + Sprint,3x10m,Wall Switch (1-1),2x10
5,F Lunge,25m,B Lunge,25m,Split Squat step ins F,x5,Laying Pigeon,25s,L Leg Scissors,2x10,...,Sled March,3x20m,Wall Runs,20s/ 10s. 4,Bird Dog Hold,2x20s,Light Tap Reaction,3x15m,NaN,NaN
6,Fire Hydrants,20,NaN,NaN,Split Squat step ins B,x5,Hamstring Lean Back,25s,R Leg Circles,2x10,...,Sled Run,4x50m,Claw Technique,2x100,NaN,NaN,NaN,NaN,NaN,NaN
7,Carioca,25m,High Knees,25m,Ankle Rotations Clockwise,2x25s,Calf Stetch,25s,L Leg Scissors,2x10,...,NaN,NaN,Lunge Jump Cycles,2x10,NaN,NaN,NaN,NaN,NaN,NaN
8,A March,25m,A Skip,25m,Ankle Rotations Counter,2x25s,Side Stretch,25s,Seated Hurdle Switch,2x10,...,NaN,NaN,SL Hops,2x10,NaN,NaN,NaN,NaN,NaN,NaN
9,B March,25m,B Skip,NaN,Knee Rotations Clockwise,2x25s,Side Lunge,25s,Donkey Kicks,2x10,...,NaN,NaN,Ankle Hops,2x10,NaN,NaN,NaN,NaN,NaN,NaN
10,Build up,6,Striders,4,Knee Rotations Counter,2x25s,It Band Stretch,25s,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,F Leg Swings,25,Lat Leg Swing,25,Calf Stretch standing,2x25s,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,Calf Stretch Ground,2x25s,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,It Band Stretch,2x25s,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [185]:
cols = list(base_df.columns)
cols[2] = 'Warm up 1'
#base_df1 = base_df.copy()
base_df.columns = cols

cols = [
    'Repetition' if pd.isna(c) else c
    for c in base_df.columns
]

base_df.columns = cols

base_df.iloc[:,:4]

         Warm up 1 Repetition      Warm up 1 Repetition
1           Scoops        25m  Frankenstiens        25m
2        Flamingos        25m   Butt Kickers        25m
3        Knee hugs        25m     Knee Pulls        25m
4      Mummy Walks        25m    Arm Circles        25m
5          F Lunge        25m        B Lunge        25m
6   Fire Hydrants          20            NaN        NaN
7          Carioca        25m     High Knees        25m
8          A March        25m         A Skip        25m
9          B March        25m         B Skip        NaN
10        Build up          6       Striders          4
11    F Leg Swings         25  Lat Leg Swing         25
12             NaN        NaN            NaN        NaN
13             NaN        NaN            NaN        NaN

In [186]:
base_df.iloc[:,0:4]

         Warm up 1 Repetition      Warm up 1 Repetition
1           Scoops        25m  Frankenstiens        25m
2        Flamingos        25m   Butt Kickers        25m
3        Knee hugs        25m     Knee Pulls        25m
4      Mummy Walks        25m    Arm Circles        25m
5          F Lunge        25m        B Lunge        25m
6   Fire Hydrants          20            NaN        NaN
7          Carioca        25m     High Knees        25m
8          A March        25m         A Skip        25m
9          B March        25m         B Skip        NaN
10        Build up          6       Striders          4
11    F Leg Swings         25  Lat Leg Swing         25
12             NaN        NaN            NaN        NaN
13             NaN        NaN            NaN        NaN

In [231]:
indexes = [
        i for i, col in enumerate(base_df.columns)
        if col != 'Repetition'
    ]

indexes

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22]

In [286]:



def split_repetitions(x):
    x = str(x).strip()

    # --- DISTANCE ONLY (m or yds) ---
    

    # --- SETS x REPS / DISTANCE / TIME ---
    if 'x' in x:
        left, right = x.split('x', 1)

        # left empty → "x2m"
        sets = int(left) if left else 1

        # right is distance
        if 'mtr' in right or 'yds' in right:
            distance = int(right.replace('yds', '').replace('mtr', ''))
            if 'yds' in right:
                distance = distance * 1.0936133
            return sets, 0, distance, 0

        # right is time
        if 'sec' in right or 'min' in right:
            if 'min' in right:
                duration = int(right.replace('min', '')) * 60
            else:
                duration = int(right.replace('sec', ''))
            return sets, 0, 0, duration

        # right is repetitions
        return sets, int(right), 0, 0

    if 'sec' in x or 'min' in x:
        if 'min' in x:
            duration = int(x.replace('min', '')) * 60
        else:
            duration = int(x.replace('sec', ''))
        return 0, 0, 0, duration
        
    if 'mtr' in x or 'yds' in x:
            distance = int(x.replace('yds', '').replace('mtr', ''))
            if 'yds' in x:
                distance = distance * 1.0936133
            return 0, 0, distance, 0
    
        # --- TIME ONLY (s, sec, min) ---
    
        
    # --- PURE REPETITIONS ---
    return 0, x, 0, 0

#sets,reps,distance,duration
split_repetitions('2x3 sec holds')

ValueError: invalid literal for int() with base 10: '3  holds'

In [285]:
# indexes

dfs = [base_dff, build_dff, peak_dff]

category_dfs = []
for df in dfs:

    suffix_map = {
        "1": "base",
        "2": "build",
        "3": "peak"
    }
    
    indexes = [
        i for i, col in enumerate(df.columns)
        if col != 'Repetition'
    ]

    import re

    def safe_unit_replace(x):
        x = str(x)
    
        # replace ONLY if the unit is at the end
        x = re.sub(r'(\d+)s$', r'\1sec', x)
        x = re.sub(r'(\d+)m$', r'\1mtr', x)
    
        return x

    for n in indexes:
        df1 = df.iloc[:, n:n+2]
        # new_header = df1.iloc[0]
        # df2 = df1.iloc[1:]
        # df2.columns = new_header
        if n == 0 :

            df1 = df.iloc[:, n:n+2]
            # new_header = df1.iloc[0]
            # df2 = df1
            # df2.columns = new_header
            ext_df = df.iloc[:,2:4]
            # new1_header = new_header
            # ext_df1 = ext_df
            
            # ext_df1.columns = new1_header
            final_df = pd.concat([df1,ext_df], ignore_index=True).fillna('zero')
            final_df['Repetition'] = final_df['Repetition'].apply(lambda x: safe_unit_replace(x))
            for key, value in suffix_map.items():
                if key in df.columns[0]:
                    final_df['Phase'] = value

            
            final_df['Sets'] = final_df['Repetition'].apply(lambda x:split_repetitions(x)[0])
            final_df['Repetition'] = final_df['Repetition'].apply(lambda x:split_repetitions(x)[1])
            final_df['Distance'] = final_df['Repetition'].apply(lambda x:split_repetitions(x)[2])
            final_df['Duration'] = final_df['Repetition'].apply(lambda x:split_repetitions(x)[3])
            category_dfs.append(final_df.dropna())

        elif n ==2:
            pass
        else:
            df1 = df.iloc[:, n:n+2].fillna(0)
            df1['Repetition'] = df1['Repetition'].apply(lambda x: safe_unit_replace(x))
            for key, value in suffix_map.items():
                if key in df.columns[0]:
                    df1['Phase'] = value
            df1['Sets'] = df1['Repetition'].apply(lambda x:split_repetitions(x)[0])
            df1['Repetition'] = df1['Repetition'].apply(lambda x:split_repetitions(x)[1])
            df1['Distance'] = df1['Repetition'].apply(lambda x:split_repetitions(x)[2])
            df1['Duration'] = df1['Repetition'].apply(lambda x:split_repetitions(x)[3])
            # new_header = df1.iloc[0]
            # df2 = df1.iloc[1:]
            # df2.columns = new_header
            category_dfs.append(df1.dropna())

        # print(new_header)
        # print(df1.columns)
        # print(ext_df1.columns)

        # print(df.iloc[:,n:n+2])

category_dfs

ValueError: too many values to unpack (expected 2)

In [284]:
str('25yds').replace('s','sec').replace('m','mtr')

'25ydsec'

In [187]:
base_df.columns

Index(['Warm up 1', 'Repetition', 'Warm up 1', 'Repetition', 'Mobility 1',
       'Repetition', 'Cool Down 1', 'Repetition', 'Hips 1', 'Repetition',
       'Core 1', 'Repetition', 'Med Ball 1', 'Repetition', 'Sled 1 (780m)',
       'Repetition', 'Plyo 1', 'Repetition', 'Posture 1', 'Repetition',
       'Sprint Reaction 1', 'Repetition', 'Wall Drills 1', 'Repetition'],
      dtype='object')

In [152]:
base_df1 = base_df.rename(columns={base_df.columns[2] : 'Warm up 1'})
base_df1

#df.rename(columns={df.columns[col_index]: 'full_name'}, inplace=True)

,Warm up 1,Warm up 1,Warm up 1,Warm up 1,Mobility 1,Warm up 1,Cool Down 1,Warm up 1,Hips 1,Warm up 1,...,Sled 1 (780m),Warm up 1,Plyo 1,Warm up 1,Posture 1,Warm up 1,Sprint Reaction 1,Warm up 1,Wall Drills 1,Warm up 1
1,Scoops,25m,Frankenstiens,25m,Front/Side Leg Swings,2x25,Flamingos,25yds,Fire Hydrants,2x10,...,ISO Hold Start,4x20m,Push-Up Start → 5 Step Sprint,10,Wall Holds,3x30s,Voice Push Up Start,4x10m,Lean Hold,4x30s
2,Flamingos,25m,Butt Kickers,25m,Ankle Alphabet,x2,Swwops,25yds,Clams,2x10,...,Sled Walk Push,2x100m,Falling Start,10,Chin Tuck Hold,3x10,Visual Drop Start,4x10m,Iso Holds,4x10s
3,Knee hugs,25m,Knee Pulls,25m,Knee Pushes,x2,Quad Pulls,25yds,Fire Hydrant Raise,2x10,...,Eccentric Sled Pull B,2x20m,Wall March,2x50,Deadbug + Wall Press,3x10,Mirror Shuffle,3x15s,March,2x10
4,Mummy Walks,25m,Arm Circles,25m,Split Squats,4x25s,5-Way Lunge,25s,R Leg Scissors,2x10,...,Sled Push,4x50m,Wall Swithces,2x50,Pelvic Thrust Slow,3x10,Head Turn + Sprint,3x10m,Wall Switch (1-1),2x10
5,F Lunge,25m,B Lunge,25m,Split Squat step ins F,x5,Laying Pigeon,25s,L Leg Scissors,2x10,...,Sled March,3x20m,Wall Runs,20s/ 10s. 4,Bird Dog Hold,2x20s,Light Tap Reaction,3x15m,NaN,NaN
6,Fire Hydrants,20,NaN,NaN,Split Squat step ins B,x5,Hamstring Lean Back,25s,R Leg Circles,2x10,...,Sled Run,4x50m,Claw Technique,2x100,NaN,NaN,NaN,NaN,NaN,NaN
7,Carioca,25m,High Knees,25m,Ankle Rotations Clockwise,2x25s,Calf Stetch,25s,L Leg Scissors,2x10,...,NaN,NaN,Lunge Jump Cycles,2x10,NaN,NaN,NaN,NaN,NaN,NaN
8,A March,25m,A Skip,25m,Ankle Rotations Counter,2x25s,Side Stretch,25s,Seated Hurdle Switch,2x10,...,NaN,NaN,SL Hops,2x10,NaN,NaN,NaN,NaN,NaN,NaN
9,B March,25m,B Skip,NaN,Knee Rotations Clockwise,2x25s,Side Lunge,25s,Donkey Kicks,2x10,...,NaN,NaN,Ankle Hops,2x10,NaN,NaN,NaN,NaN,NaN,NaN
10,Build up,6,Striders,4,Knee Rotations Counter,2x25s,It Band Stretch,25s,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,F Leg Swings,25,Lat Leg Swing,25,Calf Stretch standing,2x25s,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,Calf Stretch Ground,2x25s,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,It Band Stretch,2x25s,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [226]:
base_df.columns[0]

'Warm up1'

In [8]:
drills = ['Warm up',
 'Mobility',
 'Cool Down',
 'Hips',
 'Core',
 'Med Ball',
 'Sled',
 'Plyo',
 'Posture',
 'Sprint Reaction',
 'Wall Drills']	 

choices = []

for drill in drills:
    x = (drill.lower(), drill)
    choices.append(x)

choices

[('warm up', 'Warm up'),
 ('mobility', 'Mobility'),
 ('cool down', 'Cool Down'),
 ('hips', 'Hips'),
 ('core', 'Core'),
 ('med ball', 'Med Ball'),
 ('sled', 'Sled'),
 ('plyo', 'Plyo'),
 ('posture', 'Posture'),
 ('sprint reaction', 'Sprint Reaction'),
 ('wall drills', 'Wall Drills')]

In [1]:
track = ['100m','200m','Vert (in)','SL Hld R (s)','SL Hld L (s)','SL Bound (s)','Core (reps)','Fly Zone (s)','Sprint Mobility','Agility']		
lift = ['LJ','OVHD Thr (m)','CHST Thr (m)','OVHD SQT','Lunge MTRX','Push up Hld H (s)','Push up Hld L (s)','Push up Reps','SQT (reps)','Wall Sit (s)','Dead Hang (s)','ISO Hld R (s)','ISO Hld L (s)']

In [5]:
lift

['LJ',
 'OVHD Thr (m)',
 'CHST Thr (m)',
 'OVHD SQT',
 'Lunge MTRX',
 'Push up Hld H (s)',
 'Push up Hld L (s)',
 'Push up Reps',
 'SQT (reps)',
 'Wall Sit (s)',
 'Dead Hang (s)',
 'ISO Hld R (s)',
 'ISO Hld L (s)']

In [42]:
menu_types = [
('A1','Reaction Starts (Pure Start Speed)'),
('A2','Falling / Push-Up / 3-Point Start (Projection Day)'),
('A3','Sled Contrast (Power Tool)'),
('A4','Wicket + Short Accel Blend (Skill + Accel)'),

('B1','Build-Up → Fly 10m (Speed Exposure)'),
('B2','Fly 20m (True Upright Mechanics)'),
('B3','Sprint → Float → Sprint (Elastic Control)'),
('B4','Wickets → Fly (Frequency + Rhythm Speed)'),

('C1','Float Fly 150s (Tech+Endurance 60/40)'),
('C2','Fly 2×30m + Sled 2 (Speed Reserve Builder)'),
('C3','300m Rhythm Repeats (Lactate Rhythm 70/30)'),
('C4','Fast Finish 200s + 100s (Competition Endurance)'),

('D1','Track Tempo 100s (Classic Capacity Builder)'),
('D2','Grass Strides (Joint-Friendly Tempo)'),
('D3','Row Engine (No-Impact Conditioning)'),
('D4','Tempo + Drills Combo (Recovery Skill Day)'),

('E1','Posture Reset (Spine + Pelvis Control)'),
('E2','Wall Drill Menu (Shin Angles + Timing)'),
('E3','Rhythm + Coordination Circuit (Sprint Skill Builder)'),
('E4','Reaction + Mechanics (No Sprint Required)'),

('F1','Lower Strength (Squat + Hinge + Unilateral)'),
('F2','Upper + Trunk Strength (Posture + Arm System)'),
('F3','Athletic Strength (Total Body + Sprint Transfer)'),
('F4','Tweaks Strength Day (F45-Compatible)'),

('G1','Med Ball Power Session (Low Impact Explosion)'),
('G2','Jump + Elastic Session (Bounce + Stiffness)'),
('G3','Light Olympic Derivatives (Power Mechanics)'),

('R1','Full PT Reset (Shoulders + Hips + Trunk)'),
('R2','Lower Body Recovery (Knee Efficiency + Mobility)'),
('R3','Nervous System Reset (Recovery Tools Day)'),
('R4','PT Microdose (Daily Maintenance)'),
]


MENU_CHOICES = [
        ('A', 'Accelaration (0-30m)'),
        ('B', 'Max Velocity (30-60m)'),
        ('C', 'Speed Endurance / Technique + Endurance'),
        ('D', 'Capacity/Tempo'),
        ('E', 'Rhythm/ Mechanics / Rhythm'),
        ('F', 'Strength'),
        ('G', 'Power / Elastic'),
        ('R', 'Recovery'),
    ]


menu_cat_df = pd.DataFrame(MENU_CHOICES, columns=['code','name'])
menu_subcat_df = pd.DataFrame(menu_types, columns=['code','name'])
menu_subcat_df['category'] = menu_subcat_df['code'].apply(lambda x: x[0].strip())
menu_subcat_df['title'] = menu_subcat_df['name'].apply(lambda x : x.split('(')[0].replace(')','').strip())
menu_subcat_df['subtitle'] = menu_subcat_df['name'].apply(lambda x : x.split('(')[1].replace(')','').strip())
menu_subcat_df[['category','code','title', 'subtitle']]

,category,code,title,subtitle
0,A,A1,Reaction Starts,Pure Start Speed
1,A,A2,Falling / Push-Up / 3-Point Start,Projection Day
2,A,A3,Sled Contrast,Power Tool
3,A,A4,Wicket + Short Accel Blend,Skill + Accel
4,B,B1,Build-Up → Fly 10m,Speed Exposure
5,B,B2,Fly 20m,True Upright Mechanics
6,B,B3,Sprint → Float → Sprint,Elastic Control
7,B,B4,Wickets → Fly,Frequency + Rhythm Speed
8,C,C1,Float Fly 150s,Tech+Endurance 60/40
9,C,C2,Fly 2×30m + Sled 2,Speed Reserve Builder
10,C,C3,300m Rhythm Repeats,Lactate Rhythm 70/30
11,C,C4,Fast Finish 200s + 100s,Competition Endurance
12,D,D1,Track Tempo 100s,Classic Capacity Builder
13,D,D2,Grass Strides,Joint-Friendly Tempo
14,D,D3,Row Engine,No-Impact Conditioning
15,D,D4,Tempo + Drills Combo,Recovery Skill Day
16,E,E1,Posture Reset,Spine + Pelvis Control
17,E,E2,Wall Drill Menu,Shin Angles + Timing
18,E,E3,Rhythm + Coordination Circuit,Sprint Skill Builder
19,E,E4,Reaction + Mechanics,No Sprint Required
20,F,F1,Lower Strength,Squat + Hinge + Unilateral
21,F,F2,Upper + Trunk Strength,Posture + Arm System
22,F,F3,Athletic Strength,Total Body + Sprint Transfer
23,F,F4,Tweaks Strength Day,F45-Compatible
24,G,G1,Med Ball Power Session,Low Impact Explosion
25,G,G2,Jump + Elastic Session,Bounce + Stiffness
26,G,G3,Light Olympic Derivatives,Power Mechanics
27,R,R1,Full PT Reset,Shoulders + Hips + Trunk
28,R,R2,Lower Body Recovery,Knee Efficiency + Mobility
29,R,R3,Nervous System Reset,Recovery Tools Day
30,R,R4,PT Microdose,Daily Maintenance

In [45]:
menu_cat_df.to_csv('MENU_OPTIONS.csv')
menu_subcat_df.to_csv('DETAILED_MENU_OPTIONS.csv')

In [46]:
menu_cat_df

  code                                     name
0    A                     Accelaration (0-30m)
1    B                    Max Velocity (30-60m)
2    C  Speed Endurance / Technique + Endurance
3    D                           Capacity/Tempo
4    E               Rhythm/ Mechanics / Rhythm
5    F                                 Strength
6    G                          Power / Elastic
7    R                                 Recovery